version: '3'
services:
  db:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: new_docker_user
      POSTGRES_DB: new_docker_db
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql_data:/var/lib/postgresql/data
    networks:
      - postgresql
  ws:
    build: src/ws/.
    restart: always
    environment:
      DEST_EMAIL: ${DEST_EMAIL}
      SRC_EMAIL: ${SRC_EMAIL}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      DB_HOST: db
      DB_NAME: new_docker_db
      DB_USER: new_docker_user
      DB_PASSWORD: ${POSTGRES_PASSWORD} 
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - postgresql
  ts:
    build: src/ts/.
    restart: always
    environment:
      WS_HOST: ws
    depends_on:
      - ws
    networks:
      - postgresql

  web:
    build: src/web/.
    command: "streamlit run main.py"
    ports:
      - "8501:8501"
    volumes:
      - "./src:/usr/src/app/src"
networks:
  postgresql:
    driver: bridge
  
