version: '3'
services:
  db:
    build: ./src/db  
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: new_docker_user
      POSTGRES_DB: new_docker_db
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    networks:
      - postgresql
  ws:
    build: ./src/ws
    restart: always
    environment:
      DEST_EMAIL: ${DEST_EMAIL}
      SRC_EMAIL: ${SRC_EMAIL}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DB_HOST: db
      DB_NAME: new_docker_db
      DB_USER: new_docker_user
      DB_PASSWORD: ${POSTGRES_PASSWORD} 
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - postgresql
  ts:
    build: ./src/ts
    restart: always
    environment:
      WS_HOST: ws
    depends_on:
      - ws
    networks:
      - postgresql
networks:
  postgresql:
    driver: bridge
  
