name: CI-main

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI or API

jobs:
  Deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Ensures it runs only on main branch
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Release EC2
        env:
          PRIVATE_KEY: ${{ secrets.PROD_M5_EC2_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.PROD_M5_EC2_IP  }}
          USER_NAME: ${{ secrets.PROD_USER_NAME  }}
        run: >
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
                pwd && ls -lah && \
                docker ps && echo "---- before stopping ---" && \
                docker ps -aq | xargs docker rm -f || true && \
                docker images | xargs docker rmi -f || true && \
                docker ps && echo "---- after stopping ---" && \
                docker images && \
                curr_time=$(date +%Y%m%d-%H%M) && \
                folder_name="${curr_time}-deploy" && \
                mkdir $folder_name && cd $folder_name && \
                git clone https://github.com/vfedotovs/sslv_web_scraper.git . && pwd && \
                git switch dev-1.5.8 && ls -la && \
                cp ../.env.prod . && cp ../database.ini ./src/ws/ && \
                export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} && \
                export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} && \
                export S3_BUCKET=${{ secrets.S3_BUCKET }} && \
                ./src/db/get_last_db_backup.py && \
                cp *.sql ./src/db/ && \
                ls -l ./src/db/ && \
                docker-compose --env-file .env.prod up -d && sleep 15 && \
                docker ps
                '



