name: Deploy on main

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI or API
  push:
    branches:
      - main  # Runs only when changes are pushed to the main branch
    paths:
      - '**.py'  # Triggers only if any Python file changes

jobs:
  Deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Ensures it runs only on main branch
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Release EC2
        env:
          PRIVATE_KEY: ${{ secrets.PROD_M5_EC2_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.PROD_M5_EC2_IP  }}
          USER_NAME: ${{ secrets.PROD_USER_NAME  }}
        run: >
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key &&
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
                pwd && ls -lah && \
                docker ps && echo "---- before stopping ---" && \
                docker ps -aq | xargs docker rm -f || true && \
                docker images | xargs docker rmi -f || true && \
                docker ps && echo "---- after stopping ---" && \
                docker images && \
                curr_time=$(date +%Y%m%d-%H%M) && \
                folder_name="${curr_time}-deploy" && \
                mkdir $folder_name && cd $folder_name && \
                git clone https://github.com/vfedotovs/sslv_web_scraper.git . && pwd && \
                ls -la && \
                source ./scripts/load_secrets.sh && \
                make setup && \
                make build && \
                make up && \
                sleep 15 && \
                docker ps
                '



